### ISSUE TITLE
Masking Server IP with ENV Variable

### ISSUE THREAD

**Issue by mychaelgo** [adrianha/swapii#3]
masking ip server on deploy.sh file. What do you think? @adrianha

**Comment by adrianha** [comment]
yeah, thats good. go ahead @mychaelgo !

**Comment by adrianha** [comment]
Thank you @mychaelgo..
its already merged

**Comment by mychaelgo** [comment]
@adrianha 

![LGTM](https://lgtm.in/p/KDOkAzFWp)
